version: '2'

networks:
  test:

services:
  mysql-blockmodel:
    container_name: mysql-blockmodel
    image: mysql:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 33006:3306
    networks:
      - test