CREATE DATABASE game_db;
use game_db;

CREATE TABLE IF NOT EXISTS users (
        _id INT AUTO_INCREMENT PRIMARY KEY,
        _username VARCHAR(64) NOT NULL, 
        _time VARCHAR(32)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;